import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { GltfHandRig } from './hand/GltfHandRig.js';
import { GesturePoseLibrary } from './hand/GesturePoseLibrary.js';
import { GesturePoser } from './hand/GesturePoser.js';
import { MLGestureClassifier } from './classification/MLGestureClassifier.js';
import { RuleBasedClassifier } from './classification/RuleBasedClassifier.js';
import { PlaybackController } from './playback/PlaybackController.js';
import { PlaybackUI } from './ui/PlaybackUI.js';
import type { GestureResult } from './classification/IGestureClassifier.js';

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.0;
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
document.body.appendChild(renderer.domElement);

window.addEventListener('resize', () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});

const camera = new THREE.PerspectiveCamera(40, window.innerWidth / window.innerHeight, 0.01, 10);
camera.position.set(0.08, 0.18, 0.28);
camera.lookAt(0, 0.06, 0.04);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0xd0d0d0);

// PMREMGenerator for environment map so MeshStandardMaterial reflects correctly
const pmremGenerator = new THREE.PMREMGenerator(renderer);
pmremGenerator.compileEquirectangularShader();
scene.environment = pmremGenerator.fromScene(new RoomEnvironment()).texture;

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(0, 0.06, 0.04);
controls.update();

// Key light — warm top-left
const keyLight = new THREE.DirectionalLight(0xffffff, 3.0);
keyLight.position.set(0.8, 1.5, 0.5);
keyLight.castShadow = true;
scene.add(keyLight);

// Fill light — soft right side
const fillLight = new THREE.DirectionalLight(0xe0eaff, 1.0);
fillLight.position.set(-1.2, 0.3, 0.8);
scene.add(fillLight);

// Rim/back light — separates hand from background
const rimLight = new THREE.DirectionalLight(0xffffff, 0.6);
rimLight.position.set(0, 0.5, -1.5);
scene.add(rimLight);

// Ambient — brighter for light background
scene.add(new THREE.AmbientLight(0xffffff, 0.8));

const handRig = new GltfHandRig();
scene.add(handRig.group);

const library = new GesturePoseLibrary();
const poser = new GesturePoser(handRig, library);

const restPose = library.getPose(0);
if (restPose) handRig.setTargetPose(restPose);

const controller = new PlaybackController();

(async () => {
  // Load the robotic GLB model — falls back to procedural rig on any error
  await handRig.load('/models/robotic_hand_white.glb');

  try {
    const mlClassifier = await MLGestureClassifier.create(
      '/data/GestureClassifier.onnx',
      '/data/GestureClassifier_scaler.json'
    );
    controller.setClassifier(mlClassifier, 'ML');
  } catch {
    controller.setClassifier(new RuleBasedClassifier(), 'RuleBased');
  }

  // Auto-load the bundled sample CSV so the demo is playable immediately.
  // Try synthetic_001.myo.csv first (generated by tools/GenerateSyntheticMyo.py),
  // then fall back to sample_emg.csv.
  const csvCandidates = ['/data/synthetic_001.myo.csv', '/data/sample_emg.csv'];
  for (const url of csvCandidates) {
    try {
      const resp = await fetch(url);
      if (resp.ok) {
        const text = await resp.text();
        controller.loadFile(text);
        controller.play();
        break;
      }
    } catch {
      // Try next candidate
    }
  }
})();

new PlaybackUI(controller);

controller.addEventListener('gestureChanged', (e: Event) => {
  const result = (e as CustomEvent<{ result: GestureResult }>).detail.result;
  poser.applyResult(result);
});

const clock = new THREE.Clock();
renderer.setAnimationLoop(() => {
  const delta = clock.getDelta();
  controller.update(delta);
  poser.update(delta);
  controls.update();
  renderer.render(scene, camera);
});
